name: main

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_REPO: bluegroundltd/render-template
  PUBLIC_ECR_REGISTRY: public.ecr.aws/l2j5o5b6

jobs:
  main:
    runs-on: arc-runner-set
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::489098123993:role/github-actions-assumable-role
            aws-region: us-east-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7
      - name: Build & push to public ECR
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.PUBLIC_ECR_REGISTRY}}/${{ env.DOCKER_IMAGE_REPO }}:${{ steps.short-sha.outputs.sha }}
      - name: Test action
        uses: ./ # Uses an action in the root directory
        id: render
        with:
          template: ./testdata/template.txt
          vars: |
            name: world
      - name: Get `result` output
        run: echo "${{ steps.render.outputs.result }}"
