name: release

on:
  push:
    tags:
      - '*'

env:
  DOCKER_IMAGE: chuhlomin/render-template

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the tag
        id: get_tag
        run: echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: chuhlomin/actions/docker-build-push@main
        with:
          username: chuhlomin
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ steps.get_tag.outputs.tag }}
