name: release

on:
  push:
    tags:
      - '*'

env:
  DOCKER_IMAGE_REPO: bluegroundltd/render-template
  PUBLIC_ECR_REGISTRY: public.ecr.aws/l2j5o5b6

jobs:
  release:
    runs-on: arc-runner-set
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the tag
        id: get_tag
        run: echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::489098123993:role/github-actions-assumable-role
            aws-region: us-east-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Build & push to public ECR
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.PUBLIC_ECR_REGISTRY}}/${{ env.DOCKER_IMAGE_REPO }}:${{ steps.get_tag.outputs.tag }}

  update-tag:
    runs-on: arc-runner-set
    needs: release
    if: startsWith(github.ref, 'refs/tags/v2.')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update v2 tag
        shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git tag -f v2
          git push -f origin v2
